### ISSUE TITLE
Also Applying!

### ISSUE THREAD

**Issue by TheMadras** [BYUCS452F2021/GameScoreRepo#2]
Hey I think your project looks pretty cool (I'd love to see some other people's Terraforming Mars scores). I'm pretty experienced with full-stack development. Especially if you are looking towards TypeScript/React for your frontend and Node.js for your backend. I have production experience with both as that is what I have been working with at Qualtrics for the past 8 months. Let me know if you'd like to work together! I love the idea!

EDIT: Here are some of my thoughts just on the different parts of the project.

**Business:** I think that your revenue ideas are spot on. I especially like the premium spot for game publishers that pay because I think it is a lot easier to monetize on business to business interactions.
**Operations:** I would be happy to head up any part of the project that you would like me to. I think especially some of the frontend or the overall architecture with something like AWS is where I could fit in well. I am pretty flexible though.
**Legal:** We also need to consider the legal details of having profiles and posting scores. Something similar to typical social media user agreements may be required when someone makes an account.
**Technical:** I think getting a quick MVP is the key to success. I think getting a simple webpage up and running with something like create-react-app should be pretty achievable. As we scale, we could use something like AWS Amplitude to avoid the details of hosting ourselves.
**Social:** I definitely think word of mouth has a lot of merit. Maybe the opportunity to create specific teams and club pages with their own scores posted could help local groups encourage their own members to join and post. Conventions like SaltCON could also be good opportunities.

**Comment by NateFastar** [comment]
Glad to have you, welcome aboard!

**Comment by TheMadras** [comment]
Awesome can't wait! We should set up a slack channel for the team so we can all get in touch!
