### ISSUE TITLE
I'd love to apply!

### ISSUE THREAD

**Issue by Asht0n16** [BYUCS452F2021/GameScoreRepo#3]
This sounds like a really cool idea! I have always wondered if my family is exceptionally talented at St. Petersburg and other board games we play. Because of some weird stuff with GitHub, I haven't been let into the class organization yet, but hopefully that get's fixed soon.
I've got substantial experience using AWS, including DynamoDB, from internships and other work. I took CS 260, so I know how to make a website too, though only a basic version. I'd be more comfortable working on infrastructure and backend stuff, but I'll contribute wherever I can.
Thanks for considering me!

**Comment by NateFastar** [comment]
Glad to have you, welcome aboard!
